### ISSUE TITLE
[Suggestion] Make the roadworks event callable through the comms console

### ISSUE THREAD

**Issue by vassijoseph** [emipa606/MoreFactionInteraction#1]
I'll be starting by saying thank you for your work. Also I am sadly incompetent with programming so I couldn't do it myself.

One of the most useful things in the mod imo is the roadworks event but it is incredibly rare. Is there a chance to make it so that the event can be triggered by using the comms console? Maybe add a premium since it's you that initiates the suggestion.

In case it helps, this mod adds the choice to call for trade ships through the comms console
https://github.com/KiameV/rimworld-calltradeships

Thanks for your consideration.

**Comment by emipa606** [comment]
Looked it over and its a bit beyond what time I have over, sorry!
